### ISSUE TITLE
How to compute the heterogeneity

### ISSUE THREAD

**Issue by KL4805** [Oxfordblue7/GCFL#1]
Hi authors!
I read your paper and found it very inspiring. I have one specific enquiry, which is, how to compute the heterogeneity in Table 2. Do you have code for such computation? 
Thanks!

**Comment by Oxfordblue7** [comment]
Hi! Thank you for being interested in our work. The way of computing the heterogeneity is explained in section 4.1 of our paper. If you found anything unclear, please feel free to reach out to me.

I have uploaded the codes in ./analysis. Thanks!

**Comment by KL4805** [comment]
Great! that surely helps.

发自我的iPhone

在 2022年7月10日，16:30，Oxfordblue7 ***@***.***> 写道：

﻿

Hi! Thank you for being interested in our work. The way of computing the heterogeneity is explained in section 4.1 of our paper. If you found anything unclear, please feel free to reach out to me.

I have uploaded the codes in ./analysis. Thanks!

**Comment by Oxfordblue7** [comment]
No problem. Please cite our work if you plan to use it in your work. Thank you. :)
