### ISSUE TITLE
Any code for the analysis in table1?

### ISSUE THREAD

**Issue by JLU-Neal** [Oxfordblue7/GCFL#2]
Like Kurtosis of the degree distribution, Shortest path length, Largest component size, Clustering coefficient.

**Comment by JLU-Neal** [comment]
And I don't think it was mentioned in the paper about how p-values were calculated.

**Comment by Oxfordblue7** [comment]
Hi,

These graph properties can be computed using [NetworkX](https://networkx.org/), and the Kurtosis can be calculated using [SciPy](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.kurtosis.html). For the statistical analysis, we briefly explain in the introduction of our paper; specifically, we do T-tests and report the p-values.

Thanks.

**Comment by JLU-Neal** [comment]
Thanks for clarifying!
